# server:
#     port: 8080

# spring:
#     datasource:
#         url: jdbc:mysql://localhost:3306/mashop
#         username: root
#         password: 
#     application:
#         name: mashopapi
#     jpa:
#         hibernate:
#             ddl-auto: update
#             naming:
#                 physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.MySQL8Dialect
#                 format-sql: true
